[package]
name = "victor_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
sysinfo = "0.30.5"
tokio = { version = "1.35.1", features = ["full"] }
